import React from "react";
import Marquee from "react-fast-marquee";

const LatestNews = () => {
  return (
    <div className="flex items-center gap-3 bg-base-200 p-3">
      <p className="text-base-100 bg-secondary px-3 py-2">Latest</p>

      <Marquee className="flex gap-5" pauseOnHover={true} speed={30}>
        <p className="font-bold">
          Bangladesh's foreign exchange reserves crossed $21 billion yesterday
          after almost 10 months thanks to an increased inflow of foreign
          currency generated by remittances and export earnings.
        </p>
        <p className="font-bold">
          According to the International Monetary Fund's calculation method, the
          forex reserves stood at $21.11 billion on Sunday, up from $20.89
          billion a day earlier, as per the central bank's latest data.
        </p>
        <p className="font-bold">
          <span className="font-bold text-red-500">Remittance up as rates stabilise : </span> Remittance inflow hit
          $3.29 billion in March, the highest in any single month in the history
          of Bangladesh.
        </p>
      </Marquee>
    </div>
  );
};

export default LatestNews;
